### ISSUE TITLE
How to generate image synchronously?

### ISSUE THREAD

**Issue by iraviteja** [fuzhenn/node-svg2img#17]
How to generate the image from SVG file synchronously (without callback)?

**Comment by fuzhenn** [comment]
Unfortunately, it can't because it needs to read resources, and an async way is recommended as it won't block node's main thread.

You may consider to wrap the function to a [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) for easier use.
