### ISSUE TITLE
Javascript heap out of memory

### ISSUE THREAD

**Issue by sfs-kabra** [fuzhenn/node-svg2img#18]
Hello!
There is a new version of canvg (v1.5.4), could you please update it in your dependencies?

I've run into a problem with memory leak and there is a possibility, that the new version of canvg has a fix for this.

![selection_148](https://user-images.githubusercontent.com/38884855/50969869-720e0380-14e8-11e9-92e7-f6dc65ee732b.png)

Thanks in advance.

**Comment by fuzhenn** [comment]
Sorry, forgot this issue.
I'm on vacation now, will deal with this 1 or 2 days later.
Or could you please submit a pull request to me? I will publish later.

Thanks!

**Comment by fuzhenn** [comment]
upgrade canvg to 1.5.3 and published as 0.6.0
