### ISSUE TITLE
upgrade to canvg@3.x

### ISSUE THREAD

**Issue by fuzhenn** [fuzhenn/node-svg2img#32]

**Comment by faxemaxee** [comment]
@fuzhenn please take a look at: https://github.com/fuzhenn/node-svg2img/pull/36

I wrote a comprehensive comment there.

**Comment by faxemaxee** [comment]
@fuzhenn did it again. https://github.com/fuzhenn/node-svg2img/pull/37

I also figured out where the error in the test originates: https://github.com/canvg/canvg/blob/master/src/Document/ImageElement.ts#L69

seems to be an issue within canvg
