### ISSUE TITLE
[Bug] ReferenceError: document is not defined

### ISSUE THREAD

**Issue by codesinging** [fuzhenn/node-svg2img#46]
When I convert the svg: 
https://nodejs.org/static/images/logo.svg
I found the error:  ReferenceError: document is not defined.

**Comment by kag359six** [comment]
@codesinging Ran into the same issue. Try downgrading. I downgraded to 0.7.0 and the error no longer appears.

**Comment by ZeeCoder** [comment]
Same here.
I'm trying to render an SVG with an image with it.
The error happens whether I use a relative file path or base64 encoded string.

Using 0.7.0 fixes the issue for me for the time being :+1:

**Comment by fuzhenn** [comment]
should be fixed by #48
