### ISSUE TITLE
Considering replacing canvg and node-canvas?

### ISSUE THREAD

**Issue by yisibl** [fuzhenn/node-svg2img#61]
Hi, fuzhenn

Have you considered using [resvg-js](https://github.com/yisibl/resvg-js) instead of canvg and node-canvas? resvg is almost the fastest and most compatible SVG library.

node-canvas relies on node-gyp and postinstall, and has to be recompiled every time you install it if the version of gcc on your machine is too low. This makes for a very bad user experience.

In some scenarios,`resvg-js` is even faster than sharp.

## Benchmark

```shell
Running "resize width" suite...
  resvg-js(Rust):
    12 ops/s, ±22.66%   | fastest 🚀

  sharp:
    9 ops/s, ±64.52%    | 25% slower

  skr-canvas(Rust):
    7 ops/s, ±3.72%    | 41.67% slower

  svg2img(canvg and node-canvas):
    6 ops/s, ±16.94%    | slowest, 50% slower
```

![image](https://user-images.githubusercontent.com/2784308/138337267-6c33449f-8f89-49c8-a387-2338ffd79b6a.png)

See also https://github.com/RazrFalcon/resvg#svg-support

The migration should solve most of the problems in the current issue.

**Comment by fuzhenn** [comment]
Sure, I have no doubt about resvg's future, rust is much fancies and the performance is promising.
But I have some worries about robustness of resvg-js, as it seems resvg's test cases can be stronger comparing to canvg.

**Comment by yisibl** [comment]
咱俩别绕弯弯了，哈哈用中文说吧。

你是说：「resvg 的测试用例比 canvg 充分」？这不是说明 resvg-js 的健壮性更好吗？

**Comment by yisibl** [comment]
在这里 https://canvg.github.io/canvg/demo/index.html，canvg 测试失败的 case，resvg 都可以很好的渲染。resvg 有非常健壮的测试套件，请看：https://razrfalcon.github.io/resvg-test-suite/svg-support-table.html

![image](https://user-images.githubusercontent.com/2784308/140466951-fb6324e4-795c-4c1d-81af-b235c91679fe.png)

![image](https://user-images.githubusercontent.com/2784308/140466886-3e4d7237-6a1b-4a3e-a0c5-f765ca7e81e7.png)

在经过详细的测试和对比后我整理的一个表格，结论是 resvg 和 librsvg 各有多长，librsvg 在迁移到 Rust 后新特性和 Bug 修复会更快一些，但目前还没有发布 crate。未来，得益于 napi-rs 良好的架构，resvg-js 也可以轻松实现双引擎渲染，形成互补。

Wiki 的测试套件有更详细的边缘 case 对比：https://commons.wikimedia.org/wiki/User:JoKalliauer/SVG_test_suites/resvg_Issues_details

| 引擎     | [resvg](https://github.com/RazrFalcon/resvg/) | [librsvg](https://gitlab.gnome.org/GNOME/librsvg) | [Inkscape](https://gitlab.com/inkscape/inkscape)                                       | [Batik](http://xmlgraphics.apache.org/batik/) |
| -------- | --------------------------------------------- | ------------------------------------------------- | -------------------------------------------------------------------------------------- | --------------------------------------------- |
| 实现语言 | Rust                                          | Rust                                              | C++                                                                                    | Java                                          |
| 特点     | 轻量化，速度快 SVG1.1 兼容性最好              | 支持完整的 CSS3 选择器，文本支持较弱              | 其定位是矢量绘图软件，Node.js 中需要通过令行调用，速度最慢。支持很多浏览器都不支持的特性。 | 性能和兼容性都没有优势                        |

**Comment by fuzhenn** [comment]
要是有兴趣的话，要不一起来维护这个库吧？
你可以试试用resvg替换掉canvg，然后负责后续反馈的bug修改。
有兴趣的话，我就把你加为 collaborator

**Comment by yisibl** [comment]
好的啊，你先加我吧，我有时间的时候提个 PR。

**Comment by fuzhenn** [comment]
已经邀请啦。
友情提醒一下~ 
PR里需要带上一些基础测试，未来有人提issue以后，就能在这些测试基础上增加新的测试，这样就能保证产品质量不会崩坏了。

**Comment by yisibl** [comment]
@fuzhenn 测试用例没问题的。
