### ISSUE TITLE
permission get denied for canvg

### ISSUE THREAD

**Issue by dopecodez** [fuzhenn/node-svg2img#8]
trying to run npm install svg2img but permission get denied for canvg,
why?
Using ubuntu 16.04,
npm -v returns
5.6.0
node -v returns
v8.9.1

npm install svg2img returns

code 1
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/fuzhenn/canvg.git /home/govind/.npm/_cacache/tmp/git-clone-a723e024
npm ERR! /home/govind/.npm/_cacache/tmp/git-clone-a723e024/.git: Permission denied
npm ERR!

**Comment by fuzhenn** [comment]
I didn't reproduce your error.
The error is due to failure to clone the upstream [canvg](https://github.com/fuzhenn/canvg.git) repo.
It seems to be more likely a linux error but not a bug of svg2img.
You may need to check your ubuntu settings.

**Comment by fuzhenn** [comment]
With this merged PR (https://github.com/canvg/canvg/pull/569), svg2img doesn't need to depend on  
https://github.com/fuzhenn/canvg.git any more.
You can upgrade svg2img to 0.3.0 for the change mentioned above.
